<center>
    <img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/Logos/organization_logo/organization_logo.png" width="300" alt="cognitiveclass.ai logo"  />
</center>

<h1 align=center><font size = 5>Assignment: Notebook for Peer Assignment</font></h1>

# Introduction

Using this Python notebook you will:

1.  Understand three Chicago datasets
2.  Load the three datasets into three tables in a Db2 database
3.  Execute SQL queries to answer assignment questions

## Understand the datasets

To complete the assignment problems in this notebook you will be using three datasets that are available on the city of Chicago's Data Portal:

1.  <a href="https://data.cityofchicago.org/Health-Human-Services/Census-Data-Selected-socioeconomic-indicators-in-C/kn9c-c2s2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01">Socioeconomic Indicators in Chicago</a>
2.  <a href="https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01">Chicago Public Schools</a>
3.  <a href="https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01">Chicago Crime Data</a>

### 1. Socioeconomic Indicators in Chicago

This dataset contains a selection of six socioeconomic indicators of public health significance and a “hardship index,” for each Chicago community area, for the years 2008 – 2012.

A detailed description of this dataset and the original dataset can be obtained from the Chicago Data Portal at:
[https://data.cityofchicago.org/Health-Human-Services/Census-Data-Selected-socioeconomic-indicators-in-C/kn9c-c2s2](https://data.cityofchicago.org/Health-Human-Services/Census-Data-Selected-socioeconomic-indicators-in-C/kn9c-c2s2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

### 2. Chicago Public Schools

This dataset shows all school level performance data used to create CPS School Report Cards for the 2011-2012 school year. This dataset is provided by the city of Chicago's Data Portal.

A detailed description of this dataset and the original dataset can be obtained from the Chicago Data Portal at:
[https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t](https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

### 3. Chicago Crime Data

This dataset reflects reported incidents of crime (with the exception of murders where data exists for each victim) that occurred in the City of Chicago from 2001 to present, minus the most recent seven days.

A detailed description of this dataset and the original dataset can be obtained from the Chicago Data Portal at:
[https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2](https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

### Download the datasets

This assignment requires you to have these three tables populated with a subset of the whole datasets.

In many cases the dataset to be analyzed is available as a .CSV (comma separated values) file, perhaps on the internet. Click on the links below to download and save the datasets (.CSV files):

*   <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCensusData.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01" target="_blank">Chicago Census Data</a>

*   <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoPublicSchools.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01" target="_blank">Chicago Public Schools</a>

*   <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCrimeData.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01" target="_blank">Chicago Crime Data</a>

**NOTE:** Ensure you have downloaded the datasets using the links above instead of directly from the Chicago Data Portal. The versions linked here are subsets of the original datasets and have some of the column names modified to be more database friendly which will make it easier to complete this assignment.

### Store the datasets in database tables

To analyze the data using SQL, it first needs to be stored in the database.

While it is easier to read the dataset into a Pandas dataframe and then PERSIST it into the database as we saw in Week 3 Lab 3, it results in mapping to default datatypes which may not be optimal for SQL querying. For example a long textual field may map to a CLOB instead of a VARCHAR.

Therefore, **it is highly recommended to manually load the table using the database console LOAD tool, as indicated in Week 2 Lab 1 Part II**. The only difference with that lab is that in Step 5 of the instructions you will need to click on create "(+) New Table" and specify the name of the table you want to create and then click "Next".

<img src = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/images/LoadingData.png">

##### Now open the Db2 console, open the LOAD tool, Select / Drag the .CSV file for the first dataset, Next create a New Table, and then follow the steps on-screen instructions to load the data. Name the new tables as follows:

1.  **CENSUS_DATA**
2.  **CHICAGO_PUBLIC_SCHOOLS**
3.  **CHICAGO_CRIME_DATA**

### Connect to the database

Let us first load the SQL extension and establish a connection with the database

In [1]:
!pip install sqlalchemy==1.3.9

Requirement already satisfied: sqlalchemy==1.3.9 in d:\jeremy\lib\site-packages (1.3.9)

In [30]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In the next cell enter your db2 connection string. Recall you created Service Credentials for your Db2 instance in first lab in Week 3. From your Db2 service credentials copy everything after db2:// (except the double quote at the end) and paste it in the cell below after ibm_db_sa://

<img src ="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/images/details.png">

In [36]:
# Remember the connection string is of the format:
# %sql ibm_db_sa://my-username:my-password@my-hostname:my-port/my-db-name?security=SSL
# Enter the connection string for your Db2 on Cloud database instance below

#Since I could not create an IBM Cloud Account, I use Microsoft SQL Server instead.
#I am really sorry for the inconvenience and I hope you understand.
%sql mssql+pyodbc://sa:12345@sqlsrv

### Additional Information
In my SQL Server, I create a database called "IBMDataScienceCourseSQLDatabase". I will be using this in my code to be able to access the database.

## Problems

Now write and execute SQL queries to solve assignment problems

### Problem 1

##### Find the total number of crimes recorded in the CRIME table.

In [50]:
%%sql problem_1 <<
SELECT COUNT(*) AS TOTAL_NUM_OF_CRIMES
FROM IBMDataScienceCourseSQLDatabase.dbo.CHICAGO_CRIME_DATA

 * mssql+pyodbc://sa:***@sqlsrv
Done.
Returning data to local variable problem_1

In [51]:
problem_1

[(533,)]

### Problem 2

##### List community areas with per capita income less than 11000.

In [48]:
%%sql problem_2 <<
SELECT COMMUNITY_AREA_NAME
FROM IBMDataScienceCourseSQLDatabase.dbo.CHICAGO_CENSUS_DATA
WHERE PER_CAPITA_INCOME < 11000

 * mssql+pyodbc://sa:***@sqlsrv
Done.
Returning data to local variable problem_2

In [49]:
problem_2

[('West Garfield Park',),
 ('South Lawndale',),
 ('Fuller Park',),
 ('Riverdale',)]

### Problem 3

##### List all case numbers for crimes  involving minors?(children are not considered minors for the purposes of crime analysis)

In [140]:
%%sql problem_3 <<
SELECT CASE_NUMBER
FROM IBMDataScienceCourseSQLDatabase.dbo.CHICAGO_CRIME_DATA
WHERE DESCRIPTION NOT LIKE '%CHILD%' OR PRIMARY_TYPE NOT LIKE 'CHILDREN%'

 * mssql+pyodbc://sa:***@sqlsrv
Done.
Returning data to local variable problem_3

In [142]:
problem_3

[('HK587712',),
 ('HK456306',),
 ('HT233595',),
 ('HT133522',),
 ('HZ138551',),
 ('HS540106',),
 ('HZ534771',),
 ('HL793243',),
 ('HL149610',),
 ('HK361551',),
 ('HX552797',),
 ('HT180228',),
 ('HV243612',),
 ('HN200365',),
 ('HK108680',),
 ('HY396729',),
 ('HR271603',),
 ('HX332132',),
 ('HW303994',),
 ('HS569246',),
 ('HY234744',),
 ('HP320451',),
 ('HN484464',),
 ('JB151690',),
 ('HR582990',),
 ('HR535632',),
 ('HH486939',),
 ('HW441620',),
 ('HJ561433',),
 ('HR583513',),
 ('HX509438',),
 ('HS681158',),
 ('HK350670',),
 ('G256545',),
 ('JA272438',),
 ('HH201585',),
 ('G212935',),
 ('HL590300',),
 ('HL409680',),
 ('HM324025',),
 ('G662598',),
 ('HV353560',),
 ('HR261581',),
 ('HL680775',),
 ('HM543491',),
 ('HY167451',),
 ('HY377901',),
 ('HX225704',),
 ('HJ308632',),
 ('HV528008',),
 ('HK801112',),
 ('HS532107',),
 ('JA261898',),
 ('JA559176',),
 ('JA412895',),
 ('HY273740',),
 ('HZ224258',),
 ('HJ652747',),
 ('G040244',),
 ('HJ415128',),
 ('HV534721',),
 ('JA503725',),
 ('HM803061',),
 ('HN731220',),
 ('HP691879',),
 ('HV537004',),
 ('HR149903',),
 ('HX314361',),
 ('HV345270',),
 ('HS308747',),
 ('HK728309',),
 ('HL005270',),
 ('HY291329',),
 ('HJ678713',),
 ('HY412959',),
 ('HX155070',),
 ('HV402967',),
 ('HX332979',),
 ('HJ710634',),
 ('HX165034',),
 ('HR385117',),
 ('HS230912',),
 ('HL177398',),
 ('HH702524',),
 ('JA384163',),
 ('HJ672058',),
 ('HT368471',),
 ('HY202462',),
 ('HX354359',),
 ('HZ146741',),
 ('G376790',),
 ('HX262353',),
 ('HP317516',),
 ('HZ335434',),
 ('HS678732',),
 ('HL382289',),
 ('HM392612',),
 ('HH869886',),
 ('HR460350',),
 ('HM117889',),
 ('HR576816',),
 ('HZ372381',),
 ('HZ556726',),
 ('HN421595',),
 ('HK454598',),
 ('HH657809',),
 ('HS451246',),
 ('HH316735',),
 ('G597730',),
 ('G736811',),
 ('HT651635',),
 ('HZ432273',),
 ('G517474',),
 ('HP746347',),
 ('G056330',),
 ('HN772519',),
 ('HZ309936',),
 ('HY368284',),
 ('HL353697',),
 ('HT375934',),
 ('JA188596',),
 ('HL725506',),
 ('HV395700',),
 ('HH696901',),
 ('HT390647',),
 ('HK815196',),
 ('JA490957',),
 ('HK103473',),
 ('HM556695',),
 ('HH558381',),
 ('HK498590',),
 ('HX455839',),
 ('HR703960',),
 ('HL646682',),
 ('HV445580',),
 ('G688026',),
 ('HJ466766',),
 ('HL632721',),
 ('HP579910',),
 ('HL718742',),
 ('HP714065',),
 ('HP716225',),
 ('HW481295',),
 ('HS568476',),
 ('JB213238',),
 ('HS475732',),
 ('HS595785',),
 ('HR408597',),
 ('HT542713',),
 ('HL240985',),
 ('HJ254782',),
 ('HK561262',),
 ('HW213573',),
 ('G419948',),
 ('HL177008',),
 ('HJ639869',),
 ('HM217017',),
 ('HL388623',),
 ('HY189363',),
 ('HS498285',),
 ('HN224900',),
 ('HR387668',),
 ('HJ294892',),
 ('HL745027',),
 ('G533278',),
 ('HH827769',),
 ('HH639427',),
 ('HK771992',),
 ('HH867007',),
 ('HJ575773',),
 ('HR136920',),
 ('HT457930',),
 ('G070193',),
 ('HJ724585',),
 ('HP121474',),
 ('G198370',),
 ('HJ723825',),
 ('HJ458342',),
 ('HP558812',),
 ('HY192694',),
 ('HN472326',),
 ('HK756778',),
 ('HH741961',),
 ('JA460432',),
 ('G140454',),
 ('HX239866',),
 ('HM378171',),
 ('HW182288',),
 ('HZ295843',),
 ('HM673431',),
 ('HP352546',),
 ('HR286405',),
 ('HR195987',),
 ('HW261668',),
 ('JA496716',),
 ('JA344492',),
 ('HZ334220',),
 ('HR217367',),
 ('HV268964',),
 ('JA483294',),
 ('HT169840',),
 ('HT621306',),
 ('HS269736',),
 ('HK243330',),
 ('HH262924',),
 ('HL613433',),
 ('HY267896',),
 ('HN568531',),
 ('HT112422',),
 ('HV479133',),
 ('HV592346',),
 ('HH619797',),
 ('HZ376709',),
 ('HV573337',),
 ('HL269210',),
 ('HL567458',),
 ('HR674429',),
 ('HM200888',),
 ('HX467661',),
 ('HX448587',),
 ('HS200939',),
 ('HN335611',),
 ('HZ535494',),
 ('HX154767',),
 ('HM337445',),
 ('HM244120',),
 ('HR342598',),
 ('HL187666',),
 ('HW449676',),
 ('HS589302',),
 ('HX145326',),
 ('HN553354',),
 ('HN784049',),
 ('HJ527694',),
 ('HM303461',),
 ('HM535632',),
 ('HT353855',),
 ('G134016',),
 ('HR125162',),
 ('G496261',),
 ('HJ842548',),
 ('HN280980',),
 ('JA560123',),
 ('HY405637',),
 ('HP689703',),
 ('HR345366',),
 ('HZ242802',),
 ('HM661326',),
 ('HJ336995',),
 ('HK694552',),
 ('HJ760939',),
 ('HV366181',),
 ('HJ563089',),
 ('HH576932',),
 ('HR308948',),
 ('HK100758',),
 ('HV328581',),
 ('HV267193',),
 ('HJ620738',),
 ('HJ557529',),
 ('HS498920',),
 ('HL608698',),
 ('G323273',),
 ('HK577020',),
 ('HY365876',),
 ('HS305355',),
 ('HK162357',),
 ('HN778969',),
 ('HV185969',),
 ('HH657604',),
 ('HW555338',),
 ('HV268708',),
 ('G170513',),
 ('HW160463',),
 ('HN355411',),
 ('HK190723',),
 ('HV457847',),
 ('HW566855',),
 ('HL141298',),
 ('HR281750',),
 ('HL342355',),
 ('HX112183',),
 ('HJ624999',),
 ('HJ618818',),
 ('HR597126',),
 ('HN558484',),
 ('HR505781',),
 ('HN522324',),
 ('HN647052',),
 ('HT323138',),
 ('HW562748',),
 ('HN719188',),
 ('HT237921',),
 ('HY215032',),
 ('HK369511',),
 ('HL703172',),
 ('HM762800',),
 ('HN370211',),
 ('HR195962',),
 ('HM284854',),
 ('HL319228',),
 ('HR447925',),
 ('HM590293',),
 ('HP513177',),
 ('HL331611',),
 ('HN448271',),
 ('HH402660',),
 ('HN422493',),
 ('HP263901',),
 ('G577663',),
 ('HT535175',),
 ('JA110097',),
 ('HM360756',),
 ('HN275969',),
 ('HZ544441',),
 ('HL660560',),
 ('HS164946',),
 ('HR399710',),
 ('HP243837',),
 ('HP157774',),
 ('HP340132',),
 ('HJ388435',),
 ('JA246453',),
 ('HN407116',),
 ('JA107722',),
 ('HJ532105',),
 ('HH729144',),
 ('HY204891',),
 ('HZ228967',),
 ('HY385205',),
 ('HK328402',),
 ('JA349450',),
 ('HK743113',),
 ('HR185873',),
 ('HH692211',),
 ('JA470839',),
 ('HY182950',),
 ('HR668156',),
 ('HZ234518',),
 ('HW569852',),
 ('HS314108',),
 ('HH463517',),
 ('HN182437',),
 ('HW493063',),
 ('HJ637197',),
 ('HH829588',),
 ('HZ322965',),
 ('HW415978',),
 ('HL315870',),
 ('HJ222529',),
 ('HM535930',),
 ('HZ242203',),
 ('HN213069',),
 ('HH343366',),
 ('JA269772',),
 ('HH106347',),
 ('HM507529',),
 ('HP258815',),
 ('HL111533',),
 ('HS479338',),
 ('HZ403432',),
 ('HV462975',),
 ('HW414519',),
 ('HL414306',),
 ('HT315369',),
 ('HL330223',),
 ('HK751265',),
 ('HT540548',),
 ('HX398190',),
 ('HK348713',),
 ('HR206683',),
 ('HH154448',),
 ('JA462321',),
 ('HV233824',),
 ('HR307075',),
 ('HZ134318',),
 ('HM437597',),
 ('HW233866',),
 ('G659211',),
 ('HW274134',),
 ('HW526270',),
 ('G375927',),
 ('HP325677',),
 ('HL300450',),
 ('HN246122',),
 ('HH149573',),
 ('HK450946',),
 ('HT434553',),
 ('HL548996',),
 ('HR696852',),
 ('HK481967',),
 ('HT202584',),
 ('HJ409442',),
 ('HT251336',),
 ('HV575905',),
 ('HR489129',),
 ('HT427568',),
 ('HR539548',),
 ('HS426544',),
 ('HT556032',),
 ('HL254965',),
 ('JA216127',),
 ('HW350078',),
 ('HR308245',),
 ('HY455377',),
 ('HP747058',),
 ('HN645348',),
 ('HL334216',),
 ('HS230740',),
 ('HV593288',),
 ('HK341632',),
 ('HH859922',),
 ('G611731',),
 ('HM757133',),
 ('HJ786817',),
 ('HV356669',),
 ('HX207970',),
 ('HM733422',),
 ('HH352862',),
 ('G652158',),
 ('HX301095',),
 ('HY163644',),
 ('HR140766',),
 ('HH605275',),
 ('HJ513676',),
 ('HH337319',),
 ('HH423186',),
 ('HN543219',),
 ('HZ463811',),
 ('HN702776',),
 ('HR607189',),
 ('G654957',),
 ('HL131736',),
 ('HN519755',),
 ('G629024',),
 ('HL239939',),
 ('HK328522',),
 ('HJ349966',),
 ('G345035',),
 ('JA394755',),
 ('HY518743',),
 ('JA550741',),
 ('HH493814',),
 ('HZ523997',),
 ('G161722',),
 ('HY455698',),
 ('HH208082',),
 ('HT404945',),
 ('HL213843',),
 ('HM422467',),
 ('JA192460',),
 ('HL446401',),
 ('HS330202',),
 ('HP661088',),
 ('HJ281736',),
 ('HN136243',),
 ('HJ580490',),
 ('HV213648',),
 ('HV514287',),
 ('HJ753917',),
 ('JA133264',),
 ('HJ642080',),
 ('JA557966',),
 ('HV548880',),
 ('HR480844',),
 ('HW568748',),
 ('HH405177',),
 ('HL472862',),
 ('G326063',),
 ('HL424420',),
 ('JA393243',),
 ('HR585012',),
 ('JA455629',),
 ('HV369974',),
 ('HN637742',),
 ('HW557360',),
 ('HJ776916',),
 ('HJ419340',),
 ('HH329720',),
 ('HM802052',),
 ('HJ804627',),
 ('HR190881',),
 ('G575031',),
 ('G122095',),
 ('HN595319',),
 ('G302291',),
 ('G057394',),
 ('HM590468',),
 ('HV463112',),
 ('HK749575',),
 ('HS100098',),
 ('HW576249',),
 ('HK485601',),
 ('HH460583',),
 ('HM576559',),
 ('HL611297',),
 ('HV356389',),
 ('HX203242',),
 ('HH292682',),
 ('G635735',),
 ('HN567387',),
 ('HR391350',),
 ('HM768251',),
 ('HT394616',),
 ('HH688935',),
 ('HK677648',),
 ('G158614',),
 ('HK310265',),
 ('HR314298',),
 ('HT404326',),
 ('HY259084',),
 ('HL415544',),
 ('HP265256',),
 ('HR392537',),
 ('HL266884',),
 ('HK238408',),
 ('HX343113',),
 ('HM195342',),
 ('HW519443',),
 ('JA359626',),
 ('HN144152',),
 ('HN544458',),
 ('HW238778',),
 ('JB155558',),
 ('HY458571',),
 ('HZ378869',),
 ('HZ378355',),
 ('HX258445',),
 ('HZ192829',),
 ('HZ133234',),
 ('HJ747227',),
 ('JA143710',),
 ('G021609',)]

### Problem 4

##### List all kidnapping crimes involving a child?

In [124]:
%%sql problem_4 <<
SELECT *
FROM IBMDataScienceCourseSQLDatabase.dbo.CHICAGO_CRIME_DATA
WHERE PRIMARY_TYPE = 'Kidnapping' AND DESCRIPTION LIKE 'CHILD%'

 * mssql+pyodbc://sa:***@sqlsrv
Done.
Returning data to local variable problem_4

In [125]:
problem_4

[(5276766, 'HN144152', '2007-01-26', '050XX W VAN BUREN ST', '1792', 'KIDNAPPING', 'CHILD ABDUCTION/STRANGER', 'STREET', False, False, 1533, 15, 29, 25, '20', 1143050, 1897546, 2007, 41.874908447265625, -87.75025177001953, '(41.874908413, -87.750249307)')]

### Problem 5

##### What kinds of crimes were recorded at schools?

In [54]:
%%sql problem_5 <<
SELECT DISTINCT PRIMARY_TYPE
FROM IBMDataScienceCourseSQLDatabase.dbo.CHICAGO_CRIME_DATA
WHERE LOCATION_DESCRIPTION LIKE 'SCHOOL%'

 * mssql+pyodbc://sa:***@sqlsrv
Done.
Returning data to local variable problem_5

In [55]:
problem_5

[('ASSAULT',),
 ('BATTERY',),
 ('CRIMINAL DAMAGE',),
 ('CRIMINAL TRESPASS',),
 ('NARCOTICS',),
 ('PUBLIC PEACE VIOLATION',)]

### Problem 6

##### List the average safety score for all types of schools.

In [120]:
%%sql problem_6 <<
SELECT AVG(SAFETY_SCORE) AS AVERAGE_SAFETY_SCORE, Elementary_Middle_or_High_School
FROM IBMDataScienceCourseSQLDatabase.dbo.CHICAGO_PUBLIC_SCHOOLS
GROUP BY Elementary_Middle_or_High_School

 * mssql+pyodbc://sa:***@sqlsrv
Done.
Returning data to local variable problem_6

In [121]:
problem_6

[(49, 'ES'), (49, 'HS'), (48, 'MS')]

### Problem 7

##### List 5 community areas with highest % of households below poverty line

In [109]:
%%sql problem_7 <<
SELECT COMMUNITY_AREA_NAME, PERCENT_HOUSEHOLDS_BELOW_POVERTY
FROM IBMDataScienceCourseSQLDatabase.dbo.CHICAGO_CENSUS_DATA
ORDER BY PERCENT_HOUSEHOLDS_BELOW_POVERTY DESC
OFFSET 0 ROWS FETCH FIRST 5 ROWS ONLY

 * mssql+pyodbc://sa:***@sqlsrv
Done.
Returning data to local variable problem_7

In [110]:
problem_7

[('Riverdale', 56.5),
 ('Fuller Park', 51.20000076293945),
 ('Englewood', 46.599998474121094),
 ('North Lawndale', 43.099998474121094),
 ('East Garfield Park', 42.400001525878906)]

### Problem 8

##### Which community area is most crime prone?

In [126]:
%%sql problem_8 <<
SELECT COMMUNITY_AREA_NUMBER
FROM IBMDataScienceCourseSQLDatabase.dbo.CHICAGO_CENSUS_DATA
WHERE COMMUNITY_AREA_NUMBER IN (SELECT TOP 1 COMMUNITY_AREA_NUMBER FROM IBMDataScienceCourseSQLDatabase.dbo.CHICAGO_CRIME_DATA 
                                WHERE COMMUNITY_AREA_NUMBER IS NOT NULL GROUP BY COMMUNITY_AREA_NUMBER ORDER BY COUNT(*) DESC)

 * mssql+pyodbc://sa:***@sqlsrv
Done.
Returning data to local variable problem_8

Double-click **here** for a hint

<!--
Query for the 'community area number' that is most crime prone.
-->

In [127]:
problem_8

[(25,)]

### Problem 9

##### Use a sub-query to find the name of the community area with highest hardship index

In [103]:
%%sql problem_9 <<
SELECT COMMUNITY_AREA_NAME
FROM IBMDataScienceCourseSQLDatabase.dbo.CHICAGO_CENSUS_DATA
WHERE HARDSHIP_INDEX IN (SELECT MAX(HARDSHIP_INDEX) FROM IBMDataScienceCourseSQLDatabase.dbo.CHICAGO_CENSUS_DATA)

 * mssql+pyodbc://sa:***@sqlsrv
Done.
Returning data to local variable problem_9

In [104]:
problem_9

[('Riverdale',)]

### Problem 10

##### Use a sub-query to determine the Community Area Name with most number of crimes?

In [105]:
%%sql problem_10 <<
SELECT COMMUNITY_AREA_NAME
FROM IBMDataScienceCourseSQLDatabase.dbo.CHICAGO_CENSUS_DATA
WHERE COMMUNITY_AREA_NUMBER IN (SELECT TOP 1 COMMUNITY_AREA_NUMBER FROM IBMDataScienceCourseSQLDatabase.dbo.CHICAGO_CRIME_DATA 
                                WHERE COMMUNITY_AREA_NUMBER IS NOT NULL GROUP BY COMMUNITY_AREA_NUMBER ORDER BY COUNT(*) DESC)

 * mssql+pyodbc://sa:***@sqlsrv
Done.
Returning data to local variable problem_10

In [106]:
problem_10

[('Austin',)]

Copyright © 2020 [cognitiveclass.ai](cognitiveclass.ai?utm_source=bducopyrightlink&utm_medium=dswb&utm_campaign=bdu). This notebook and its source code are released under the terms of the [MIT License](https://bigdatauniversity.com/mit-license?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ).

## Author(s)

<h4> Hima Vasudevan </h4>
<h4> Rav Ahuja </h4>
<h4> Ramesh Sannreddy </h4>

## Contribtuor(s)

<h4> Malika Singla </h4>

## Change log

| Date       | Version | Changed by        | Change Description                             |
| ---------- | ------- | ----------------- | ---------------------------------------------- |
| 2021-11-17 | 2.6     | Lakshmi           | Updated library                                |
| 2021-05-19 | 2.4     | Lakshmi Holla     | Updated the question                           |
| 2021-04-30 | 2.3     | Malika Singla     | Updated the libraries                          |
| 2021-01-15 | 2.2     | Rav Ahuja         | Removed problem 11 and fixed changelog         |
| 2020-11-25 | 2.1     | Ramesh Sannareddy | Updated the problem statements, and datasets   |
| 2020-09-05 | 2.0     | Malika Singla     | Moved lab to course repo in GitLab             |
| 2018-07-18 | 1.0     | Rav Ahuja         | Several updates including loading instructions |
| 2018-05-04 | 0.1     | Hima Vasudevan    | Created initial version                        |

## <h3 align="center"> © IBM Corporation 2020. All rights reserved. <h3/>